---
  - name: NGINX - install nginx service
    yum:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: httpd_result
    until: nginx_result is success
    retries: 3
    delay: 5

  - name: HTTPD - upload 00-mpm.conf custom settings /etc/httpd/conf.modules.d/00-mpm.conf
    template:
      src: etc/httpd/conf.modules.d/00-mpm.conf.j2
      dest: /etc/httpd/conf.modules.d/00-mpm.conf
      owner: root
      group: root
      mode: 0644

  - name: HTTPD - enable and start service httpd
    systemd:
      name: httpd
      enabled: yes
      state: started

  - name: HTTPD - append vagrant user to apache group
    user:
      name: vagrant
      groups: apache
      append: yes
      state: present

  - name: HTTPD - alter /var/www/html folder ownership
    file:
      path: /var/www/html
      owner: apache
      group: apache
      mode: u=rwx,g=rwx,o=r
      follow: yes # Previous to Ansible 2.5, this was no by default.

#  - debug:
#      var: httpd_result

#  - debug:
#      var: hostvars